### ISSUE TITLE
outside cluster flag unnecessary

### ISSUE THREAD

**Issue by deitch** [plunder-app/kube-vip#101]
We use [outsidecluster](https://github.com/plunder-app/kube-vip/blob/d82fd174b4a3c936a73cd0780486591b0e63bfe5/pkg/service/manager.go#L88) as a flag to indicate we are outside the cluster.

Is there any reason we cannot do it the way kubectl does (or used to, last time I looked at its code), or cloud-provider? I think it basically does the following:

1. looks for `KUBECONFIG` env var or `--kubeconfig` cmd-line option, if found, use that
1. looks for the default in-cluster config (service account)
1. error out

**Comment by thebsdbox** [comment]
It's another throw back from testing, it will probably be removed later down the line :)

**Comment by thebsdbox** [comment]
Fixed in `0.3.0` including documentation.
