### ISSUE TITLE
Missing arm packages in docker hub

### ISSUE THREAD

**Issue by anagno** [plunder-app/kube-vip#112]
Hello Everyone,

The last 3 releases (https://hub.docker.com/r/plndr/kube-vip/tags) are missing the arm packages. Probably were forgotten?

KR,
Vasileios

**Comment by thebsdbox** [comment]
Strange. I wonder if I've broken the `makefile` I'll have them all up tomorrow (except 0.2.2, that hasn't been released yet) 🙃

**Comment by thebsdbox** [comment]
`0.2.0` didn't have a real release as it was a quick patch.. 

I've added the missing images for `0.2.1` and `0.2.2`.. This process will be automated at some point in the future.

**Comment by anagno** [comment]
Thanks !
