### ISSUE TITLE
Support Multiple CIDRs for global or namespaced VIPs

### ISSUE THREAD

**Issue by vrabbi** [plunder-app/kube-vip#122]
in environments with an existing network with segmented IPs already allocated the ability to assign multiple CIDRs for a specific namespace or for the global setting would be very beneficial.
i have a use case for service type load balancer using the global option for a VIP range but the available IPs are multiple /29 CIDRs all in the same L2 network.

a similar setup to MetalLB in this sense with multiple network ranges being supported would be very beneficial in such situations

**Comment by thebsdbox** [comment]
https://github.com/plunder-app/plndr-cloud-provider/pull/30
