### ISSUE TITLE
Allow IP Ranges instead of CIDRs for VIPs

### ISSUE THREAD

**Issue by vrabbi** [plunder-app/kube-vip#123]
many times especially if using the ARP mechanism for Service Type LB, the available ranges of IPs to be used as VIPs may not match with a valid CIDR. this could be either that the number of IPs is not that of a CIDR notation or that the starting IP of an available range falls in the previous CIDR.  

example:
network: 172.16.20.0/24
IP range wanted for VIPs: 172.16.20.10-172.16.20.40

the best solution from my perspective would be supporting a range value instead of a CIDR notation similar to the MEtalLB configuration. another option is to support multiple CIDRs for a specific use #122 and by this while not an elegant solution someone with this use case could allocate a multitude of /32 CIDRs to kube-vip for a specific namespace or for the global VIP range.

If this is added it should allow if possible for multiple ranges

example CM value
cidr-global: 172.16.20.10-172.16.20.40,172.16.20.50-172.16.20.70

**Comment by thebsdbox** [comment]
I like the ranges over cidr’s although in hindsight. This isn’t the job of `kube-vip`.. it’s down to the CCM! If you’re using the plunder-cloud provider then we’d need to add the logic there.

**Comment by vrabbi** [comment]
I am using plndr
Should.i open a similar issue on that repo? If and once that merges this issue remains valid I believe as a docs issue

**Comment by thebsdbox** [comment]
https://github.com/plunder-app/plndr-cloud-provider/pull/30

**Comment by thebsdbox** [comment]
https://github.com/plunder-app/plndr-cloud-provider/pull/30
Fixed in 0.1.5 of the cloud provider.
