### ISSUE TITLE
Inverted port assignments

### ISSUE THREAD

**Issue by nickperry** [plunder-app/kube-vip#13]
In https://github.com/plunder-app/kube-vip/blob/master/kubernetes-control-plane.md the kube-vip and kube-apiserver port assignments are inverted between the kube-vip config and the kube init params. I.e. you've swapped who is 6443 and who is 6444.

**Comment by nickperry** [comment]
And in the kubeadm join

**Comment by thebsdbox** [comment]
This is now fixed
