### ISSUE TITLE
Manifest building without docker

### ISSUE THREAD

**Issue by blinkiz** [plunder-app/kube-vip#130]
This is an enhancement request within the control plane functionality.

I do not use docker and Kubernetes has now deprecated docker.
How can I get kube-vip to work without docker? Is it possible to generate the manifest with crictl? Maybe kube-vip can provide a ready manifest to use in documentation so docker is not needed?

**Comment by thebsdbox** [comment]
Sure thing! it's entirely possible to do the same things with `podman` or `crictl`.. The Kube-Vip manifest <pod|daemonset> commands are helpers to generate kubernetes manifests, we could also release `Kube-Vip` binaries that people could run locally? Alternatively there is also kube-vip.io/manifests/ but I need to generate some scripting to auto-generate them for releases.

**Comment by blinkiz** [comment]
Sounds great. In my opinion the best future proof solution would be to have manifest examples ready in the documentation. That way there is no dependencies against external tool to get kube-vip to work. If there is a need to generate something maybe have the user (me) drop bootstrap manifest in kubelet that generates the correct manifest. Still no need for external tool, just kubelet.

But for me crictl instructions in documentation would also work which in theory should work against all CRI runtimes in Kubernetes.

**Comment by thebsdbox** [comment]
Documentation has been updated for the `hybrid` design.

**Comment by blinkiz** [comment]
I just tried the hybrid solution and it worked.
I used `ctr` and the fix in #142.

**Comment by thebsdbox** [comment]
Example manifests do exists in the documentation -> https://github.com/plunder-app/kube-vip/tree/master/docs/manifests

**Comment by vrabbi** [comment]
possibly releasing a set of manifests as assets of each release? similar to other projects like CAPI or the rabbitmq clustert operator as examples? that way it would be easy to know for each release what the relevant manifest would be

**Comment by thebsdbox** [comment]
Good idea!

**Comment by thebsdbox** [comment]
Fixed in #159
