### ISSUE TITLE
Support multiple BGP upstream peer configuration

### ISSUE THREAD

**Issue by goshlanguage** [plunder-app/kube-vip#132]
As an end user, I have a need to support and configure multiple upstream BGP peers. 

It looks as though work may had begun on this previous and was commented out, but I am not sure if that's right or not:
https://github.com/plunder-app/kube-vip/blob/master/cmd/kube-vip-config.go#L49-L58

Thank you for your help.

**Comment by thebsdbox** [comment]
If we use the Packet API, with `--packet` then it will automatically find all peers from the API. To specify this manually the `--bgppeers` flag has been added.

**Comment by thebsdbox** [comment]
^This will be closed when 0.2.3 is merged into main.
