### ISSUE TITLE
containerd kube-vip alias is not working

### ISSUE THREAD

**Issue by mhuttner** [plunder-app/kube-vip#142]
I tried to set 

`alias kube-vip="ctr run --rm --net-host docker.io/plndr/kube-vip:0.2.3 vip`
and then
```
kube-vip manifest pod \
    --interface $INTERFACE \
    --vip $VIP \
    --controlplane \
    --services \
    --arp \
    --leaderElection
```
as described in
https://github.com/plunder-app/kube-vip/blob/master/docs/hybrid/static/index.md .

With containerd 1.4.3 I get the error
`ctr: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "manifest": executable file not found in $PATH: unknown`
because the "manifest" is seen as the [CMD] argument to ctr.

**Solution:**
I fixed this by setting
`alias kube-vip="ctr run --rm --net-host docker.io/plndr/kube-vip:0.2.3 vip /kube-vip"` 
instead, this should probably be updated in the docs. 

 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: v1.19
 - Kube-vip Version: 0.2.3
 - containerd 1.4.3

**Comment by thebsdbox** [comment]
Good catch! Would you like to raise a PR? Or I can?
