### ISSUE TITLE
kube-vip arm/v7 images in dockerhub ?

### ISSUE THREAD

**Issue by grunlab** [plunder-app/kube-vip#147]
arm/v7 images are not available for all kube-vip versions.
Here is the current status in dockerhub (https://hub.docker.com/r/plndr/kube-vip/tags?page=1&ordering=last_updated):

- 0.3.0 --> arm/v7 image available but kube-vip version 0.3.0 is not yet mentioned in the documentation (https://kube-vip.io/hybrid/#changelog) so I don't really know if I can start using it or not?
- 0.2.3 --> arm/v7 image not available
- 0.2.2 --> arm/v7 image not available
- 0.2.1 --> arm/v7 image looks available but I'm not able to pull it:
```
root@master-02:~# podman pull plndr/kube-vip:0.2.1
Completed short name "plndr/kube-vip" with unqualified-search registries (origin: /etc/containers/registries.conf)
Trying to pull docker.io/plndr/kube-vip:0.2.1...
  unsupported docker v2s2 media type: "application/vnd.oci.image.layer.v1.tar+gzip"
Trying to pull quay.io/plndr/kube-vip:0.2.1...
  unauthorized: access to the requested resource is not authorized
Error: 2 errors occurred while pulling:
 * Error initializing image from source docker://plndr/kube-vip:0.2.1: unsupported docker v2s2 media type: "application/vnd.oci.image.layer.v1.tar+gzip"
 * Error initializing source docker://quay.io/plndr/kube-vip:0.2.1: Error reading manifest 0.2.1 in quay.io/plndr/kube-vip: unauthorized: access to the requested resource is not authorized
```
- 0.2.0 --> arm/v7 image not available

**Comment by thebsdbox** [comment]
`0.3.0` is the recommended release.. I just haven't had the opportunity to finish it before the holidays... I'll try and complete it today/tomorrow.

**Comment by thebsdbox** [comment]
All images should now be auto-generated.
