### ISSUE TITLE
kube-vip supports ipv6?

### ISSUE THREAD

**Issue by luniHw** [plunder-app/kube-vip#155]
**Describe the bug**
1. set a ipv6 address for kube-vip
2. fail to start kube-vip container
root [ /var/log ]# crictl --runtime-endpoint /var/run/containerd/containerd.sock logs fbf204b4a0c40
time="2021-01-05T00:56:36Z" level=fatal msg="Unable to find local address"

**To Reproduce**

**Expected behavior**

Hope kube-vip suppports ipv6

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804]
 - Kubernetes Version: [e.g. v.1.18]
 - Kube-vip Version: [e.g. 0.2.3]

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_address
      value: 2020::250:56ff:fe81:ef3f
    - name: vip_interface
      value: eth0
    - name: vip_leaseduration
      value: "15"
    - name: vip_renewdeadline
      value: "10"
    - name: vip_retryperiod
      value: "2"

**Additional context**

**Comment by thebsdbox** [comment]
Not yet... Its on a roadmap that I need to write :-)

**Comment by rosenhouse** [comment]
I’m pretty interested in this, and can try to take a first crack at it.

I’m thinking I’ll start with L2 support / NDP.

**Comment by thebsdbox** [comment]
That would be great.. I don't think it would be overly complicated to implement.. we'd just need to extend the section around advertising (https://github.com/plunder-app/kube-vip/blob/e2f8628211c2cb92a17907303b74241e623da6ca/pkg/cluster/singleNode.go#L109) etc..

**Comment by thebsdbox** [comment]
@rosenhouse if you need any help, please let me know :)

**Comment by thebsdbox** [comment]
Hey @rosenhouse How are you getting on, do you need any assistance?

**Comment by rosenhouse** [comment]
Hey @thebsdbox thanks for checking in!  Got distracted, but looking at this again now with another dev on my team.

I don't think we need anything right now.  We're reading up on gratuitous NDP, looking at how it's implemented in other projects, and thinking through how we might write a test to cover it.

**Comment by rosenhouse** [comment]
So, we've got a first, thin thread implemented in #185 ^^^ 

Depending on how that looks, we could consider hitting the other cases (L3, service type:LB, daemonset) in some order...

**Comment by thebsdbox** [comment]
Awesome sauce ! Thanks everyone !!
