### ISSUE TITLE
Is network addons needed ?

### ISSUE THREAD

**Issue by rwanito** [plunder-app/kube-vip#161]
Hi !

I'm new in the kubernetes world.
So, maybe my question will be useless !
And I don't know where to ask this question..., if my question shouldn't be there, free to close it !

When I setup the HA system, like kube-vip, do I need to use a network addons like calico or weavenet ?
And why ?

Thanks a lot for your attention !

**Comment by thebsdbox** [comment]
So the answer is that it depends, For HA then no as the Kubernetes pods will be deployed as static pods and those exist largely outside of the cluster itself.. for service `type loadbalancer` then yes a CNI plugin will probably be needed.

**Comment by rwanito** [comment]
Okay thanks !
If I want to have 3 masters servers and 3 workers servers to work together (loadbalancer), I need a CNI plugin ?

To init this, 
I need to first create the manifest of kubevip.
make kubeadm init.

And which one in first : 
- join other nodes
- or setup the cni plugin ?

Do you have a suggestion about cni plugin ? I think I'll go on calico.

**Comment by thebsdbox** [comment]
I normally opt for Calico, with regards to your question.. the choice is entirely yours :-) the CNI plugin runs as a daemonset so once deployed you don't need to think about it.

**Comment by rwanito** [comment]
Thanks you very much for your help !
It will help me a lot !
