### ISSUE TITLE
does the --ddns flag exist?

### ISSUE THREAD

**Issue by PeterGarner** [plunder-app/kube-vip#171]
As described on this page https://kube-vip.io/control-plane/,  "A new flag --ddns is introduced. Once enabled, kube-vip expects the input --address will be a FQDN etc" 

Following instructions, I've tried variations of 

sudo docker run --network host \
    --rm plndr/kube-vip:0.3.2 \
    manifest pod \
    --interface ens192 \
    --address "my-kubu-vip-addr" \
    --ddns "true"\
    --arp \
    --leaderElection | sudo tee /etc/kubernetes/manifests/vip.yaml

I'm in home lab environment on a 192.168.0.0/16 network, my router provides leases. 
Ubuntu 20.04
kubelet/kubeadm 1.20.4-00
kube-vip 0.3.2

My expectation was that a new IP would be provided by my home router DNS and get assigned to the --address FQDN, but I get 

Error: unknown flag: --ddns
unknown flag: --ddns
Usage:
  kube-vip manifest pod [flags]

**Comment by PeterGarner** [comment]
I built the main Dockerfile from this repo but got the same with that image. Also the ran the Makefile (make all) and got a binary with the same (not so familiar with Go).  Any pointers please?

**Comment by thebsdbox** [comment]
Ah! I'm a fool, it was never migrated over to the hybrid UX.. i'll raise a PR and get that fixed, and update the tests.

https://github.com/plunder-app/kube-vip/blob/afdbac7a58c9b629c80e6057a5fb4bd23d6feaa7/cmd/kube-vip-start.go#L31
