### ISSUE TITLE
[Question] - how load balancing works with control plane virtual IP?

### ISSUE THREAD

**Issue by AndrewBoklashko** [plunder-app/kube-vip#172]
Basically, is it actually load balancing traffic between API servers on different nodes or it's just doing a failover?

**Comment by thebsdbox** [comment]
It is up to the end user, by default it's just doing HA.. however it can also perform https load balancing. We're looking at implementing pics for it in future too.

**Comment by AndrewBoklashko** [comment]
@thebsdbox can you clarify on how to configure the load balancing? Or point me to the documentation page where it's described.

**Comment by AndrewBoklashko** [comment]
Still waiting here..

**Comment by thebsdbox** [comment]
https://kube-vip.io/architecture/#load-balancing-(outside-a-cluster)

The old documentation is there, I would (if possible) hang fire and i'll look into implementing IPVS support.

**Comment by AndrewBoklashko** [comment]
Thanks for the link, finally got it after looking at source code. The `config` flag which allows to provide additional configuration.
So I was confused initially because for example this [page](https://kube-vip.io/hybrid) does not provide any flags to configure load balancing or additional configuration file.

IPVS support would be awesome, but proxy LB should work fine for me as well.
