### ISSUE TITLE
Additional RBAC permissions required in 1.20.2

### ISSUE THREAD

**Issue by oskapt** [plunder-app/kube-vip#177]
**Describe the bug**

Following the docs results in RBAC errors in the logs.

**To Reproduce**

1. Perform DaemonSet installation on K3s 1.20.2+k3s1
2. Look at the logs

**Fix**

Add the following to `kube-vip-rbac.yaml`

```
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
```

kube-vip 0.3.2 on K3s 1.20.2+k3s1

**Comment by davidasnider** [comment]
I just confirmed on k3s v1.20.4+k3s1 that this addition to the rbac fixes kube-vip in my cluster.

**Comment by thebsdbox** [comment]
Ah, this is on me ... all the k3s testing was done using BGP and not ARP, which doesn't require leader election.

**Comment by thebsdbox** [comment]
Added into `rbac.yaml`
