### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by chipzoller** [plunder-app/kube-vip#180]
**Is your feature request related to a problem? Please describe.**
There are no installation instructions anywhere in the documentation that I can find.

**Describe the solution you'd like**
Create installation instructions for users to follow.

**Comment by thebsdbox** [comment]
All documentation is in the /docs folder .. for installation or usage it's down to the operating or deployment model (either as a static pod or a daemonset)

Docs are -> https://github.com/plunder-app/kube-vip/tree/master/docs/hybrid
