### ISSUE TITLE
kube-vip.io/k3s throws a 404

### ISSUE THREAD

**Issue by bgulla** [plunder-app/kube-vip#189]
**Describe the bug**
The latest docs point to `curl -sL kube-vip.io/k3s` for the k3s install instructions but the endpoint throws a 404.

**To Reproduce**
1. Go to 'https://kube-vip.io/control-plane/'
2. `curl -sL kube-vip.io/k3s` produces a 404

**Expected behavior**
This used to pull down a deployment that matched the unique filepaths for `k3s` specific installations but now a user must hand-edit the standard deployment and guess where the file translations lie.

**Screenshots**
```bash
@k3box[~/k3s] > curl -sL kube-vip.io/k3s
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at kube-vip.io Port 443</address>
</body></html>
```

**Environment (please complete the following information):**
```bash
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
```

**Comment by thebsdbox** [comment]
Doh.. I had to recreate the entire kube-vip.io site recently.. I'll get the k3s script back shortly.

**Comment by thebsdbox** [comment]
Fixed -> 

```
$ curl -sL kube-vip.io/k3s | vipAddress=192.168.0.10 vipInterface=ens192 sh
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
```

**Comment by bgulla** [comment]
thanks!
