### ISSUE TITLE
Inconsistent version numbering on Github releases and image tags

### ISSUE THREAD

**Issue by HubbeKing** [plunder-app/kube-vip#194]
**Describe the bug**
On github, the latest release is v0.3.3, released today.
On Docker Hub, the latest tag is 0.3.4, pushed about a day ago, and 0.3.3 was pushed about a month back.
Additionally, the latest tag with an image for all three architectures is 0.3.2, the 0.3.3 and 0.3.4 tags only have amd64 images.

**To Reproduce**
1. Check releases on https://github.com/plunder-app/kube-vip/releases
2. Check image tags on https://hub.docker.com/r/plndr/kube-vip/tags?page=1&ordering=last_updated

**Expected behavior**
Consistency between release versions and image tags on Docker Hub.
Release v0.3.3 should have a 0.3.3 image tag, with properly pushed images for amd64, arm64, and arm/v7

**Comment by thebsdbox** [comment]
This is now completely automated through GitHub Actions! 🔥
