### ISSUE TITLE
digineo/go-dhclient has Limited GPL License

### ISSUE THREAD

**Issue by TerryHowe** [plunder-app/kube-vip#202]
**Is your feature request related to a problem? Please describe.**
digineo/go-dhclient has a GPL license which limits the usability of of kube-vip

**Describe the solution you'd like**
There are plenty of other dhcp clients out there and most likely another has a more permissive license.

**Describe alternatives you've considered**
Switch to another client with a permissive license such as https://github.com/insomniacslk/dhcp

**Comment by thebsdbox** [comment]
Makes sense, i'll investigate it tomorrow !

**Comment by thebsdbox** [comment]
Taking a little longer than expected.. we use DHCP in two places in slightly different ways and there isn't a single replacement that offers the same functionality. So i'm having to write my own at this point :-|

**Comment by thebsdbox** [comment]
Fixed in #203
