### ISSUE TITLE
How does kube-vip compare to MetlalLB?

### ISSUE THREAD

**Issue by lentzi90** [plunder-app/kube-vip#30]
Cool project!
My immediate thought when reading about kube-vip was "How does this compare to [MetalLB](https://metallb.universe.tf/)?".
I think it would be good to add to the readme how it differs, and if there are situations where one is preferred over the other. Unfortunately I don't know the answers myself or I would already have opened a PR!

Specifically, I think MetalLB's [layer 2 mode](https://metallb.universe.tf/configuration/#layer-2-configuration) seems to be exactly the same as wat kube-vip is doing.

**Comment by thebsdbox** [comment]
I'll put something together soon, I'm putting a lot together on https://kube-vip.io 

One thing to be aware of:
https://metallb.universe.tf/concepts/layer2/ <- `kube-vip` is always load-balancing itself and failover is typically in 3.5 seconds.

**Comment by thebsdbox** [comment]
At the moment the `type: LoadBalancer` is very similar to metallb, the main focus at this time is on the control plane HA which is something that metallb doesn't provide. I've a plan to add additional functionality to the in-cluster load-balancer that may provide different functionality in the future that other load balancers don't provide. Until that time, I'll close this issue (feel free to request it open if needed).
