### ISSUE TITLE
Remove duplicate data from configmap

### ISSUE THREAD

**Issue by thebsdbox** [plunder-app/kube-vip#34]
Instead of populating the configmap with vip/protocol/port etc.. pull information directly from service mentioned in configmap

**Comment by pickledrick** [comment]
for now should we leave this as a ConfigMap with a reference to the `namespace/configmapname` that we are load balancing, perhaps if we require more structured data and authorization around these resources we could transition to a CRD produced by plndr that kube-vip consumes, that way we could update status field and have custom printed fields when performing GETs of CRD resources etc.

If we were to use the data in an existing cm for example

```
data:
  plndr-services: '{"services":[{"vip":"10.176.37.249","port":80,"type":"TCP","uid":"e14c9d7a-00a4-4b09-a3ee-338c85143477","serviceName":"nginx-loadbalancer"},{"vip":"10.176.37.250","port":80,"type":"TCP","uid":"6ece0038-fd89-4ab5-a81a-ab9f4bd87a35","serviceName":"kuard"}]}'
```

I feel we would still need vip, port (as a service could have multiple and we may not want to LB all of them), and type (as we may want to be explicit)

cc @thebsdbox

**Comment by thebsdbox** [comment]
OK, tbh I had a plan when I wrote this to do something better and it's been that long (and so much has happened) that I can't remember what I was planning on doing.

**Comment by thebsdbox** [comment]
We no longer use the ConfigMap as we make user of the Kubernetes API directly.
