### ISSUE TITLE
question - can I use LoadBalancer Service without the kube-vip loadbalancer ?

### ISSUE THREAD

**Issue by cameronbraid** [plunder-app/kube-vip#48]
Is it possible to configure kube-vip so that it just assigns the IP address to the service, and get kube proxy to do the load balancing ?

**Comment by thebsdbox** [comment]
At this point, `kube-vip` will load-balance the traffic that hits the Load Balancer VIP. It could be modified so that it just passes traffic to the internal service IP and leaves the traffic to be passed internally (using kube-proxy). 

Is this something that people might want?

**Comment by thebsdbox** [comment]
This was done in `0.2.1` ! 🎉
