### ISSUE TITLE
Documentation Site github repo

### ISSUE THREAD

**Issue by crocswearer** [plunder-app/kube-vip#59]
Hello,

I am wanting to raise a PR for docs https://kube-vip.io is there a public repo for this?

**Comment by thebsdbox** [comment]
There is not right now (this morning) but I'll get something sorted so people can access the markdown. They were something I threw up one weekend in a rush

**Comment by RytisLT** [comment]
@thebsdbox https://kube-vip.io/control-plane/ document is incorrect. The `--leaderElection=true` flag is missing, therefore kube-vip tries to work with raft in kubernetes cluster.

**Comment by thebsdbox** [comment]
Documentation flag is fixed, and the docs are now in `0.2.1` 🌮
