### ISSUE TITLE
K3s installation steps

### ISSUE THREAD

**Issue by thebsdbox** [plunder-app/kube-vip#75]
Create local directory for BD storage
`mkdir mysql`

Start Docker MySQL container
`sudo docker run --cap-add SYS_NICE -p 3306:3306 --name k3s-mysql -v /home/dan/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=k3s-password -d mysql:8 `

Set VIP
`export VIP=192.168.0.40 `

Create Manifest directory (before) starting k3s
`sudo mkdir -p /var/lib/rancher/k3s/server/manifests/`

Create kube-vip manifest (needs turning into daemonset)
`sudo docker run --network host --rm plndr/kube-vip:0.1.8 kubeadm init --interface ens160 --vip $VIP --arp --leaderElection | sed 's/name: kube-vip/name: kube-vip-'`hostname`'/g' |  sed 's/path: \/etc\/kubernetes\/admin.conf/path: \/etc\/rancher\/k3s\/k3s.yaml/g' |  sudo tee /var/lib/rancher/k3s/server/manifests/vip.yaml`

Start `k3s`
`sudo ./k3s server --tls-san $VIP --datastore-endpoint="mysql://root:k3s-password@tcp(192.168.0.43:3306)/kubernetes"`

Grab configuration and point it to the VIP address
```
  mkdir -p $HOME/.kube
  sudo cat /etc/rancher/k3s/k3s.yaml | sed 's/127.0.0.1/'$VIP'/g' > $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
```

Get`Node` token
`sudo cat /var/lib/rancher/k3s/server/node-token`

Alternative install method and notes (TODO - investigate later on)
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 \
--datastore-endpoint mysql://root:k3s-password@tcp(192.168.0.43:3306)/kubernetes \
-t agent-secret --tls-san $VIP \
--node-taint k3s-controlplane=true:NoExecute" sh -

or 

sudo K3S_TOKEN= ./k3s server --server https://192.168.0.40:6443
```

cc /@oskapt

**Comment by alexellis** [comment]
Docker isn't usually installed to k3s hosts, that's part of the beauty and speed of the solution..

Therefore it'd be nice if you had the equivalent of the below:

```
sudo docker run --network host --rm plndr/kube-vip:0.1.8 kubeadm init --interface ens160 --vip $VIP --arp --leaderElection | sed 's/name: kube-vip/name: kube-vip-'hostname'/g' | sed 's/path: \/etc\/kubernetes\/admin.conf/path: \/etc\/rancher\/k3s\/k3s.yaml/g' | sudo tee /var/lib/rancher/k3s/server/manifests/vip.yaml
```

But that ran as a static binary or a bash file.

When we spoke, you had a concern of the size of your binary. You could publish a tiny binary to do this one task, that'd be the easiest to maintain and a clean approach, you could hack some bash, or zip your binary.. zipping for us reduced the size of inletsctl from 30-35mb to 10mb. https://github.com/inlets/inletsctl/releases

**Comment by alexellis** [comment]
Keep up the good work. I'm looking forward to telling people about Kube-vip for a HA k3s control plane IP.

**Comment by thebsdbox** [comment]
These steps need an alternative method that doesn't involve the Docker engine. Perhaps `curl -sFL kube-vip.io/k3sManifest.yaml | sed 's/old_IP/new_IP/' > manifest.yaml`

**Comment by thebsdbox** [comment]
Right, here we go !

**Option one:**

`curl -sL kube-vip.io/k3s | vipAddress=192.168.0.10 vipInterface=ens192 sh > /var/lib/rancher/k3s/server/manifests/vip.yaml`

**Option two:**

```
export vipAddress=192.168.0.10
export vipInterface=ens192
curl -sL kube-vip.io/k3s | sh > /var/lib/rancher/k3s/server/manifests/vip.yaml
```

**Comment by thebsdbox** [comment]
This is now added to the documentation.
