### ISSUE TITLE
Enable kube-vip to resolve DNS entries and use the IP as a vip_address

### ISSUE THREAD

**Issue by yastij** [plunder-app/kube-vip#79]
to enable DNS support, we should be able to resolve a DNS entry and use it a VIP for ARP broadcasting

**Comment by thebsdbox** [comment]
I think that this can be closed with the merge of #84 @yastij ?

**Comment by yastij** [comment]
Correct

**Comment by dhawal55** [comment]
Any update on when v0.1.9 will be released?

**Comment by thebsdbox** [comment]
It's behind schedule as I've been pretty busy of late.. is there any particular function that you're after that is in the roadmap for `0.1.9` ?

**Comment by dhawal55** [comment]
I'm interested in this particular issue (use DNS entry instead of IP) and
my understanding is this will be available in v0.1.9 release
